### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by syphernl** [jseidl/ha-room#1]
I have defined 7 rooms in my HA config. For these all of the rooms have a presence hold switch created but only 1 of the 7 rooms actually have a binary_sensor. I have restarted HA but they still do not show up. 

Room that shows up:
```yaml
  toilet:
    name: "Toilet"
    presence_sensors:
      - binary_sensor.pir_toilet_sensor
    icon: 'mdi:toilet'
```

Rooms that do not show up:
```yaml
  living_room:
    name: "Woonkamer"
    presence_sensors:
      - binary_sensor.woonkamer_pir_motion
      - media_player.tv
    presence_hold_sensors:
      - media_player.tv
    icon: 'mdi:sofa'

  kitchen:
    name: "Keuken"
    presence_sensors:
      - binary_sensor.keuken_pir_motion
    icon: 'mdi:chef-hat'
```

The logs show the follow exception:
```
Dec 15 11:46:08 hass hass[16147]: 2019-12-15 11:46:08 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Dec 15 11:46:08 hass hass[16147]: Traceback (most recent call last):
Dec 15 11:46:08 hass hass[16147]:   File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 406, in _async_add_entity
Dec 15 11:46:08 hass hass[16147]:     await entity.async_added_to_hass()
Dec 15 11:46:08 hass hass[16147]:   File "/home/hass/.homeassistant/custom_components/room/binary_sensor.py", line 85, in async_added_to_hass
Dec 15 11:46:08 hass hass[16147]:     self.update_state()
Dec 15 11:46:08 hass hass[16147]:   File "/home/hass/.homeassistant/custom_components/room/binary_sensor.py", line 128, in update_state
Dec 15 11:46:08 hass hass[16147]:     if self.hass.states.get(sensor).state in self.room.on_states:
Dec 15 11:46:08 hass hass[16147]: AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by jseidl** [comment]
The log would infer that one of your entities does not exists (typo?). One test you could do is remove all `presence_sensors` and add them one at a time and see which one is failing.

**Comment by syphernl** [comment]
But since only 1 out of 7 rooms shows up that would mean that 6 out of 7 rooms have entities that do not exist? I have copied their id's from the states page.

I'll try adding them one by one.

**Comment by syphernl** [comment]
The first one is already failing to show up:
```yaml
room:
  living_room:
    name: "Woonkamer"
    presence_sensors:
      - binary_sensor.woonkamer_pir_motion
      - media_player.tv
    presence_hold_sensors:
      - media_player.tv
    icon: 'mdi:sofa'
```

Both entities exist and are currently set to the `off` state.

**Comment by jseidl** [comment]
Well the error you're getting in your log is due to the entity not being found. Might be related, might not, but we'll get to the bottom of it :) 

I just pushed an update that will handle this error (It will add a log error with the actual sensor that is not found), you might give it a spin

**Comment by jseidl** [comment]
> The first one is already failing to show up:
> 
> ```yaml
> room:
>   living_room:
>     name: "Woonkamer"
>     presence_sensors:
>       - binary_sensor.woonkamer_pir_motion
>       - media_player.tv
>     presence_hold_sensors:
>       - media_player.tv
>     icon: 'mdi:sofa'
> ```
> 
> Both entities exist and are currently set to the `off` state.

What happens if you set living room with only and the same entities as the one that is working (toilet) ?

**Comment by syphernl** [comment]
With the update its more clear what's going wrong:
```
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.woonkamer_pir_motion entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.keuken_pir_motion entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.pir_toilet_sensor entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.slaapkamer_pir_motion entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.pir_bathroom_sensor entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.werkkamer_pir_motion entity is not found
Dec 15 12:14:25 hass hass[24092]: 2019-12-15 12:14:25 ERROR (MainThread) [custom_components.room.binary_sensor] binary_sensor.pir_zolder_sensor entity is not found
```

It's missing all my PIR sensors. But that's normal during the startup of HA, since they are connected via Zigbee2MQTT and it usually a short while for them to be initialized by HA.

**Comment by jseidl** [comment]
Are the `binary_sensor`s still failing to appear? With the exception being handled it shouldn't prevent the entity from being created.

**Comment by syphernl** [comment]
> Are the `binary_sensor`s still failing to appear? With the exception being handled it shouldn't prevent the entity from being created.

Ah yeah, the all did show up fine now! However.. it doesn't appear they actually work. All sensors are clear even though I am triggering the motion sensor in my office.

**Comment by jseidl** [comment]
Can you test and reply on this thread if it's working so we can close this issue:?

Note: Possibly fixed on https://github.com/jseidl/ha-room/commit/3b703ef5a8e08750df37f14f0bf5830eaf2a9dca

**Comment by syphernl** [comment]
> Can you test and reply on this thread if it's working so we can close this issue:?
> 
> Note: Possibly fixed on [3b703ef](https://github.com/jseidl/ha-room/commit/3b703ef5a8e08750df37f14f0bf5830eaf2a9dca)

The  `binary_sensors` for all rooms show up fine now. However: None of them are changing status even though PIR's were triggered.

**Comment by jseidl** [comment]
Yeah I was afraid you'd have this problem since the `binary_sensor` call `track_state_change` on those entities on startup.

You're probably using discovery right? I'll have to dig a little more on that. I use my sensors over MQTT too but I explicitly define them over `yaml`. You can try this (it is some work) meanwhile.

**Comment by jseidl** [comment]
Created a new issue to address the race-condition between `ha-room` and discoverable components. 
@syphernl we might continue this debug on this new issue. 

Thanks for reporting this `AttributeError` bug, hopefully I'll be able to address the discovery one.
